"""add email and receive_reminders to User

Revision ID: 33c8d5f15fa1
Revises: cb3fda909c7a
Create Date: 2025-09-15 21:26:01.484478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c8d5f15fa1'
down_revision: Union[str, Sequence[str], None] = 'cb3fda909c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('receive_reminders', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'receive_reminders')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
