"""upd UserWord

Revision ID: cb3fda909c7a
Revises: 38c5507e299d
Create Date: 2025-09-14 19:54:13.714907

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cb3fda909c7a'
down_revision: Union[str, Sequence[str], None] = '38c5507e299d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('easiness', sa.Float(), nullable=False, server_default="2.5"))
    op.add_column('user_words', sa.Column('interval', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('user_words', sa.Column('next_review', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('user_words', sa.Column('reviews_count', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_words', 'reviews_count')
    op.drop_column('user_words', 'next_review')
    op.drop_column('user_words', 'interval')
    op.drop_column('user_words', 'easiness')
    # ### end Alembic commands ###
